# Systems of Linear Equations - Quiz

## Introduction
The following scenarios present problems that can be solved as system of equations, while performing substitutions and eliminations as you saw in the previous lesson. 

* Solve these problems by hand, showing all the steps to work out the unknown variable values 
* Verify your answers by showing the calculated values satisfy all equations

## Objectives
You will be able to:
* Describe a system of linear equations for solving simple analytical problems
* Solve a system of equations using elimination and substitution

## Exercise 1
Jane paid 12 dollars for 4 cups of coffee and 4 cups of tea. 3 cups of coffee cost as much as 2 cups of tea. What would be the total cost of 5 cups of coffee and 5 cups of tea?

### Solution

> Let $x$ be the unit price of coffee and $y$ be the unit price of tea

In [10]:
import numpy as np

In [11]:
# # Equation version
# 12 = 4x + 4y
# 0 = 2y - 3x
# total_cost = 5x + 5y

# # Matrix version
# [12, 0] = [[4, 4], [3, -2]] * [x, y]

In [13]:
# Python version
cups = np.array([[4,4], [3,-2]])
cost = np.array([12,0])
final_cost = np.linalg.solve(cups, cost)
final_cost #this is the cost per coffee and per tea

array([1.2, 1.8])

In [14]:
# cost_5_cups = final_cost*np.array([5,5]).transpose()
# cost_5_cups

# cost5 = final_cost*np.array([5,5]).T
# cost5

cost6 = np.dot(final_cost, np.array([5,5]))
cost6

15.0

## Exercise 2

Jim has more money than Bob. If Jim gave Bob 20 dollars, they would have the same amount. If Bob gave Jim 22 dollars, however, Jim would then have twice as much as Bob. 

How much does each one actually have?

### Solution
> Let x be the amount of money that Jim has and y be the amount that Bob has.

In [19]:
# x = amount of money Jim has
# y = amount of money Bob has 

# x - 20 = y + 20
# x = y + 40
# 40 = x - y

# y - 22 = 2x + 44 
# y = 2x + 66 
# 66 = y - 2x 

money_both = np.array([[1,-1], [-2,1]])
total_money = np.array([40,66])
each_money = np.linalg.solve(money_both, total_money) 
each_money


array([-106., -146.])

## Exercise 3

Mia has 30 coins, consisting of quarters (25 cents) and dimes (10 cents), which totals to the amount 5.70 dollars.  
How many of each does she have?

### Solution

In [23]:
# 30 = x + y
# 5.7 = 0.25x + 0.10y 
# 570 = 25x + 10y 
# 114 = 5x + 2y

mia_money = np.array([[5,2],[1,1]])
total_money = np.array([114,30])
each_mia_money = np.linalg.solve(mia_money, total_money) 
each_mia_money 


array([18., 12.])

## Level up - Optional 
For more pratice with linear equations, Visit following links for more complex equations and online answers verification:

* https://www.transum.org/software/SW/Starter_of_the_day/Students/Simultaneous_Equations.asp?Level=6
* https://www.transum.org/software/SW/Starter_of_the_day/Students/Simultaneous_Equations.asp?Level=7

## Summary
In this lesson, you learned how to solve linear equations by hand to find the co-efficient values. You'll now move forward to have a deeper look into vectors and matrices and how Python and Numpy can help us solve more complex equations in an analytical context. 